name: PyTest

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - nane: Build package
        uses: messense/maturin-action@v1
        with:
          manylinux: auto
          command: build
          args: --release -o dist
      - name: Install dependencies
        run: |
          python -m pip install .
          python -m pip install pytest
      - name: Run test suite
        run: |
          python -m pytest
